### ISSUE TITLE
phpdotevn

### ISSUE THREAD

**Issue by xPhantomNL** [Setitch/php-jira-api-rest-client#2]
This version requires phpdotenv ~1.0, while laravel 5.2.31 requires phpdotenv ~2.2 and lesstif/php-jira-rest-client requires phpdotevn ~2.2.

This project, at the moment, cannot be used with laravel 5.2.31.

**Comment by Setitch** [comment]
I'm not sorry about that - there is version 2.2+ and its never than 1+ so i will stick to the newer one. If you want i can make a release that dont use dotenv at all (as most php is used with normal php stack not iis). It that is ok with you, just tell.

**Comment by Setitch** [comment]
As author ignores question - closing.
